export const MAXIMUM_USERS_FOR_ONE_ROOM = 5;
export const SECONDS_TIMER_BEFORE_START_GAME = 10;
export const SECONDS_FOR_GAME = 100;
export const SECONDS_BOT_UPDATES_CURRENT_STATE = 30;
export const SECONDS_BOT_PAUSE_BEFORE_JOKE = 8;
export const STEPS_AWAY_FROM_FINISH_TO_CHECK_LEADER = 30;
